Repository Tresjs/post-processing, pull requests merged in 2025-01, with the labels that each got.

#150 feat: add scanline
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/pmdrs/ScanlineDemo.vue
  docs/components.d.ts
  docs/guide/pmndrs/scanline.md
  playground/src/pages/postprocessing/scanline.vue
  playground/src/router.ts
  src/core/pmndrs/ScanlinePmndrs.vue
  src/core/pmndrs/index.ts
Labels: feature, p3-significant

#149 feat: add chromatic aberration effect
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/pmdrs/ChromaticAberrationDemo.vue
  docs/components.d.ts
  docs/guide/pmndrs/chromatic-aberration.md
  playground/src/pages/postprocessing/chromatic-aberration.vue
  playground/src/router.ts
  src/core/pmndrs/ChromaticAberration.vue
  src/core/pmndrs/index.ts
Labels: feature, p3-significant

#172 feat: kuwahara
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/pmdrs/KuwaharaDemo.vue
  docs/components.d.ts
  docs/guide/pmndrs/kuwahara.md
  playground/src/pages/postprocessing/kuwahara.vue
  playground/src/router.ts
  src/core/pmndrs/KuwaharaPmndrs.vue
  src/core/pmndrs/custom/kuwahara/index.ts
  src/core/pmndrs/index.ts
Labels: p3-significant

#175 fix: typescript-build-issues related to DepthPicking and Linocut
  src/core/pmndrs/DepthPickingPassPmndrs.vue
  src/core/pmndrs/LinocutPmndrs.vue
  src/core/pmndrs/index.ts
Labels: bug, types

#179 fix: add exported member depth picking pass pmndrs
  src/core/pmndrs/index.ts
  src/core/three/UnrealBloom.vue
Labels: bug, p4-important-bug
